title: deepe
author: Stealthcopter
logo: /images/logo.png
description: Container enumeration and exploitation script
show_downloads: false
theme: jekyll-theme-hacker
collections:
  tests:
    output: true
  guides:
    output: true

defaults:
  - scope:
      path: "_tests"
    values:
      test: true
