# Run all the container tests and publish to github pages
name: ContainerTests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install required tools
      run: sudo apt install -y aha

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check docker is installed
      run: docker ps -a

    - name: Run all container tests
      run: | 
       cd tests 
       ./run-all.sh

    - name: Showing all logs
      run: |
       ls -lah tests/results
       tail -n +1 tests/results/*.log

    - name: Upload all logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: tests/results/

    - name: Copy test results
      run: cp -r tests/results /tmp/results
        
    - name: Switch to gh-pages
      uses: actions/checkout@v2        
      with:
        ref: 'gh-pages'
        clean: true
      
    # Checkout gh-pages branch
    - name: Copy test results into branch
      run: |
        ls -lah /tmp/results
        rm -rf results
        cp /tmp/results results
        ls -lah ./results
        
    # Checkout gh-pages branch
    - name: Push Changes
      run: |
        git status
        git config --global user.name 'stealthcopter-ci'
        git config --global user.email 'stealthcopter@users.noreply.github.com'
        git commit -am "Automated update from CI"

