# This is a basic workflow to help you get started with Actions

name: ContainerTests

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout code
      uses: actions/checkout@v2

    # Check docker is installed
    - name: Check docker is installed
      run: docker ps -a

    # Runs all container tests
    - name: Run all tests
      run: | 
       cd tests 
       ./run-all.sh

    # Show all logs
    - name: Showing logs
      run: |
       ls -lah tests/results
       tail -n +1 tests/results/*.log

    # Upload logs
    - name: Upload logs
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: tests/results/

    # Checkout gh-pages branch
    - name: Switch to gh-pages
      run: |
        cp -r tests/results /tmp/results
        git checkout gh-pages
        ls -lah
        ls -lah /tmp/results
